### ISSUE TITLE
restart a service using s6-rc

### ISSUE THREAD

**Issue by tdeva14** [skarnet/s6-rc#3]
So far I have been using -u/-d change options to bring up or bring down a service. Is there a way to restart the service without have to run two commands?

**Comment by skarnet** [comment]
Yes: make a script invoking `s6-rc -d change $foo` then `s6-rc -u change $foo`. ;-)
Seriously: the reason is that restarting a service via s6-rc will do exactly that. Note that it will also stop all the services that depend on `$foo`, and will not restart them since the -u line doesn't list them.

The way to quickly restart a service, without bothering with dependency chains, is to do it via s6 directly, without going through the s6-rc mechanisms: `s6-svc -r /run/service/$foo`.

**Comment by tdeva14** [comment]
Thanks much! `s6-svc -r` is what I was looking for 👍
