### ISSUE TITLE
s6-echo? s6-hostname?

### ISSUE THREAD

**Issue by subnut** [skarnet/s6-rc#5]
Inside `examples/source/00/up`, I see -
```
if { s6-echo "init-stage2 starting." }
s6-hostname foo.example.com
```
Hmm.. s6-echo and s6-hostname are no longer included in s6...

This intrigued me. Why did these programs exist in the first place?
I mean, what is wrong with the usual `echo` that you needed to write 
a new `s6-echo` for yourself?

---

Vim or Emacs? Or something else? :grinning:

**Comment by skarnet** [comment]
They were never in s6; they're in [s6-portable-utils](https://skarnet.org/software/s6-portable-utils/).
`s6-hostname`  is from a time when busybox wasn't as prevalent as it is today, and I needed to boot a system without coreutils and util-linux. As for `s6-echo`,  there are excellent reasons _not_ to use `echo`; you can read some of them [here](https://www.etalabs.net/sh_tricks.html).
I have never cared about editor wars and will use whatever is available. When I have a choice, my preference is vi, just because it's lighter.
