### ISSUE TITLE
s6-rc Oneshot Fails with Timeout

### ISSUE THREAD

**Issue by NateMeyer** [skarnet/s6-rc#8]
I'm trying to add a oneshot service as a dependency to an existing s6-rc longrun service.  The oneshot script takes up to a few minutes to run to prepare some data, but I get a failure due to a timeout about halfway through and the longrun service never starts.  My understanding from the documentation was the oneshot should never timeout unless an explicit timeout-up file was given.  I had tried adding a 10-minute timeout-up file, but I still get a timeout in less than a minute.

What would be causing this timeout? Is there a time limit to oneshot tasks?

**Comment by skarnet** [comment]
- As far as s6-rc (and any project that isn't s6-overlay) is concerned, I only use GitHub as a backup location for source code, not as a place to discuss issues, because I have no control over the archives, cannot grep in them, cannot guarantee their long time availability, etc. For discussions about s6-rc, please use the [supervision mailing-list](https://skarnet.org/lists/#supervision) instead.
- That said, indeed your understanding is correct and there shouldn't be a timeout here. My guess is that you are in fact using [s6-overlay](https://github.com/just-containers/s6-overlay/tree/master#readme) and are experiencing the default timeout. From the [v3 notes](https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md):

> There is a global timeout for all the services, adjustable via the S6_CMD_WAIT_FOR_SERVICES_MAXTIME variable. You can disable it via setting this variable to 0.

**Comment by NateMeyer** [comment]
Thanks! Yes, this is using the s6-overlay.  I'll take a look through the v3 notes and if I have further questions I'll open an issue over there.
